version: "3.8"


services:
  db:
    image: postgres:14-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ${app_ROOT:-.}:/usr/app
      - ~/.ipython:/root/ipython
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      gunicorn src.unigram.wsgi:application
        --name app-gunicorn
        --bind 0.0.0.0:8000
        --workers 4
        --pythonpath /usr/app/src
        --log-level=debug
        --reload
        --timeout 120


volumes:
  dbdata:
