version: "3.8"


services:
  db:
    image: postgres:14-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}


  app:
    build: .
    env_file:
      - .env
    volumes:
      - ${app_ROOT:-.}:/usr/app
      - ~/.ipython:/root/ipython
    depends_on:
      - db
    ports:
      - "8000:8000"



volumes:
  dbdata:
