# Generated by Django 4.1.3 on 2023-02-04 03:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_program_id_alter_university_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
